name: MERN Sample App - Frontend Tests

on:
  push:
    paths:
      - "packages/frontend/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout Repository
        uses: actions/checkout@v4

      - name: 🤳 Install
        uses: ./.github/composite-actions/install

      - name: 🚀 Run Frontend Tests
        run: pnpm run frontend:test
